### ISSUE TITLE
Could you add LICENSE file?

### ISSUE THREAD

**Issue by AtsushiHashimoto** [maxkapur/assignment#1]
Thanks for your excellent work!
We are using the repository for our project but having difficulty due to the missing license information.

It would be very helpful if you could add any license information. MIT or BSD v3 may be convenient for us (and other users) since there might be no dependency with GPL-licensed code. Then, we will refer to this repository from our work.

P.S. We found some errors in the part to organize the rotation poset but maybe we could fix them. We will send a pull request soon.

**Comment by maxkapur** [comment]
Thanks for bringing this to my attention. I've added a BSD 2-clause license (which is actually slightly more permissive than the the BSD 3-clause license that you mentioned).

I'd love it if you could identify or fix any bugs in the algorithms!

**Comment by AtsushiHashimoto** [comment]
@maxkapur Thank you very much for your prompt action! An intern student of my team will send the pull request in a few days!
